### ISSUE TITLE
Error This relationship field has the following invalid relationships: 6545bee1525dd1edc2e5362a 0

### ISSUE THREAD

**Issue by georgiev-anton** [payloadcms/plugin-relationship-object-ids#2]
Hello. I get an error on version payloadcms 2.0.15 when I try to save a document

```
{
    "errors": [
        {
            "name": "ValidationError",
            "data": [
                {
                    "field": "offerId",
                    "message": "This relationship field has the following invalid relationships: 6545bee1525dd1edc2e5362a 0"
                }
            ],
            "message": "The following field is invalid: offerId"
        }
    ]
}
```

**Comment by PatrikKozak** [comment]
Hey @georgiev-anton - we have fix merged for this. PR is [here](https://github.com/payloadcms/payload/pull/4689). 

Once we get new release published for Payload, we'll update this plugin with the new version and this will be taken care of.

Thanks for bringing this to our attention!

**Comment by PatrikKozak** [comment]
@georgiev-anton - a new version of Payload has been released since the merge of the fix. So, if you go ahead and update payload to latest (e.g. `2.8.2`) in your project, the issue above should be resolved.

**Comment by georgiev-anton** [comment]
thanks)

**Comment by NazarBashinskiy** [comment]
@PatrikKozak I have faced with the same issue when I apply filterOptions to relationship
```{
      name: 'table',
      label: 'table',
      type: 'relationship',
      relationTo: 'table',
      index: true,
      filterOptions: () => ({
        parentItem: {
          exists: false,
        }
      }),
    },```
This works fine either I turn off the plugin or turn off the filterOptions

**Comment by Rikhart** [comment]
@PatrikKozak  I have the same problem, the plugin dont work for the last version of payload.

**Comment by smoglica** [comment]
@PatrikKozak 

With payload `2.14.0` I have the same issue. When providing `filterOptions` I cannot save:

![Screenshot from 2024-04-25 15-11-34](https://github.com/payloadcms/plugin-relationship-object-ids/assets/17332096/56cfe086-cd65-42cb-b92c-098298d9d140)

Using this field definition

```ts
    ...,
    {
      name: 'parent',
      type: 'relationship',
      filterOptions: ({ id }) => ({ id: { not_equals: id } }),
      relationTo: COMMENTS,
      admin: {
        position: 'sidebar',
      },
    },
    ...
```

Response that I got

```json
    "errors": [
        {
            "name": "ValidationError",
            "data": [
                {
                    "field": "parent",
                    "message": "This field has the following invalid selections: \"662988dfe6a5d3ec7593e07b\", "
                }
            ],
            "message": "The following field is invalid: parent"
        }
    ]
```

**Comment by PatrikKozak** [comment]
Hey @smoglica @Rikhart @NazarBashinskiy @georgiev-anton - thanks for bringing this to my attention! 

I was able to get this fixed - in the process we will also be transferring this package to the Payload monorepo. 

PRs for this are here:

- v2: https://github.com/payloadcms/payload/pull/6044
- v3 (beta): https://github.com/payloadcms/payload/pull/6045

We'll get these merged asap.
